config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  scope :completed, -> { where(status: true) }
  scope :todo, -> { where(status: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  def index
    @todos = Todo.todo
    @completed = Todo.completed
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo, notice: "Todo was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to @todo, notice: "Todo was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy!

    if @todo.destroyed?
      redirect_to todos_path, notice: "Todo was successfully destroyed.", status: :see_other
    else
      redirect_to todos_path, alert: "Todo could not be destroyed.", status: :unprocessable_entity
    end
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:title, :description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo With Weather Intermediate Assessment" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <% unless Rails.env.test? %>
      <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <% end %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "todos/theme_selector" %>

    <main class="container mx-auto mt-8 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, class: "contents") do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul class="list-disc ml-6">
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": todo.errors[:title].none?, "border-red-400 focus:outline-red-600": todo.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": todo.errors[:description].none?, "border-red-400 focus:outline-red-600": todo.errors[:description].any?}] %>
  </div>

  <div class="my-5 flex items-center gap-2">
    <%= form.label :status, "Complete" %>
    <%= form.check_box :status, class: ["block shadow-sm rounded-md border order-first h-5 w-5", {"border-gray-400 focus:outline-blue-600": todo.errors[:status].none?, "border-red-400 focus:outline-red-600": todo.errors[:status].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/todos/_theme_selector.html.erb
<div class="flex items-center py-8 px-8" data-controller="theme">
  <%= radio_button_tag :dark_mode, "on", false,
    class: "mx-4",
    id: "dark-mode-toggle",
    data: { action: "change->theme#change", theme_target: "darkRadio" }
  %>
  <label for="dark-mode-toggle">Dark Mode</label>

  <%= radio_button_tag :dark_mode, "off", true,
    class: "mx-4",
    id: "light-mode-toggle",
    data: { action: "change->theme#change", theme_target: "lightRadio" }
  %>
  <label for="light-mode-toggle">Light Mode</label>
</div>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <h2 class="text-lg font-semibold"><%= todo.title %></h2>
    <p><%= todo.description %></p>
  </div>
</div>

app/views/todos/edit.html.erb
<% content_for :title, "Editing todo" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Show this todo", @todo, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
  <%= link_to "Back to todos", todos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
</div>

app/views/todos/index.html.erb
<% content_for :title, "Todos" %>

<div class="w-full" data-controller="geolocation">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-6">
    <button data-action="click->geolocation#requestLocation" data-geolocation-target="button" class="rounded-md px-3.5 py-2.5 bg-purple-600 hover:bg-purple-500 text-white font-medium cursor-pointer">
      Weather View
    </button>
    <div data-geolocation-target="result"></div>
  </div>

  <div class="grid lg:grid-cols-2 sm:grid-cols-1 gap-8 justify-between items-center">    
    <div id="todos" class="min-w-full self-baseline grid">
      <h1 class="font-bold text-4xl">Todos</h1>

      <% if @todos.any? %>
        <% @todos.each do |todo| %>
          <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0 border-2 border-gray-300 border-solid rounded-md p-5 mt-6">
            <%= render todo %>
            <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
              <%= link_to "Show", todo, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
              <%= link_to "Edit", edit_todo_path(todo), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
              <%= button_to "Destroy", todo, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-500 hover:bg-red-400 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        <% end %>
      
        <div class="mt-6">
          <%= link_to "New todo", new_todo_path, class: "rounded-md px-3 py-2 bg-blue-600 hover:bg-blue-500 text-white text-center block font-medium mb-4" %>
        </div>

      <% else %>
        <p class="text-center my-10">No todos found.</p>
      <% end %>
    </div>

    <div id="todos" class="min-w-full self-baseline">
      <h1 class="font-bold text-4xl">Completed</h1>

      <% if @completed.any? %>
        <% @completed.each do |todo| %>
          <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0 border-2 border-gray-300 border-solid rounded-md p-5 my-6">
            <%= render todo %>
            <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
              <%= link_to "Show", todo, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
              <%= link_to "Edit", edit_todo_path(todo), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
              <%= button_to "Destroy", todo, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-500 hover:bg-red-400 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Back to todos", todos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
</div>

app/views/todos/show.html.erb
<% content_for :title, "Showing todo" %>

<div class="md:w-2/3 w-full border-2 border-gray-300 border-solid rounded-md p-5 my-6">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing todo</h1>

  <%= render @todo %>

  <%= link_to "Edit this todo", edit_todo_path(@todo), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
  <%= link_to "Back to todos", todos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-700 text-white hover:bg-gray-600 inline-block font-medium" %>
  <%= button_to "Destroy this todo", @todo, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-500 hover:bg-red-400 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>